"""on delete cascade

Revision ID: ac7de1823fda
Revises: 8a877af400b1
Create Date: 2025-07-17 15:11:01.389244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac7de1823fda'
down_revision: Union[str, Sequence[str], None] = '8a877af400b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('product_images_product_id_fkey'), 'product_images', type_='foreignkey')
    op.create_foreign_key(None, 'product_images', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('product_parameters_product_id_fkey'), 'product_parameters', type_='foreignkey')
    op.create_foreign_key(None, 'product_parameters', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_parameters', type_='foreignkey')
    op.create_foreign_key(op.f('product_parameters_product_id_fkey'), 'product_parameters', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.create_foreign_key(op.f('product_images_product_id_fkey'), 'product_images', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
